### ISSUE TITLE
Typo in raster_tools.py

### ISSUE THREAD

**Issue by maximlamare** [robertxa/pyswath#2]
Hi, 

I'm trying to run your code, but I believe there is a typo. 

In raster_tools.py, line 277:

``
gdal.ReprojectImage(rasterdata, dst,  src.ExportToWkt(), srs_new.ExportToWkt(), GRA_Bilinear) 
``

src is not defined. Looking at the code in the lines above, I believe it should read:

``
gdal.ReprojectImage(rasterdata, dst,  srs.ExportToWkt(), srs_new.ExportToWkt(), GRA_Bilinear) 
``

**Comment by wehrad** [comment]
Hi,

I made the same observation, totally agree!

**Comment by robertxa** [comment]
Hi,

Thanks, I corrected it !
